<?php
$root = $this->baseUrl();
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('EIA');
//if ($this->header == NULL)
//    $this->header = '<!-- /.navbar -->
//        <header id="head"><div class="container">
//                <div class="heading-text">							
//                    <h1 class="animated flipInY delay1">Sistema de </h1>
//                    <p>Materias Cursadas en el semestre</p>
//                </div>
//
//                <div class="fluid_container">                       
//                    <div class="camera_wrap camera_emboss pattern_1" id="camera_wrap_4">
//                        <div data-thumb="' . $root . '/assets/images/slides/thumbs/img1.jpg" data-src="' . $root . 'assets/images/slides/img1.jpg">
//                            <h2>We develop.</h2>
//                        </div> 
//                        <div data-thumb="' . $root . '/assets/images/slides/thumbs/img2.jpg" data-src="' . $root . 'assets/images/slides/img2.jpg">
//                        </div>
//                        <div data-thumb="' . $root . '/assets/images/slides/thumbs/img3.jpg" data-src="' . $root . 'assets/images/slides/img3.jpg">
//                        </div> 
//                    </div> #camera_wrap_3 
//                </div> .fluid_container 
//            </div>
//        </header>';
echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <?php echo $this->headMeta(); ?>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <?php echo $this->headTitle(); ?>
        <link rel="favicon" href="<?php echo $root; ?>/assets/images/favicon.png"/>
        <link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700"/>
        <link rel="stylesheet" href="<?php echo $root; ?>/assets/css/bootstrap.min.css"/>
        <link rel="stylesheet" href="<?php echo $root; ?>/assets/css/font-awesome.min.css"/> 
        <link rel="stylesheet" href="<?php echo $root; ?>/assets/css/bootstrap-theme.css" media="screen"/> 
        <link rel="stylesheet" href="<?php echo $root; ?>/assets/css/style.css"/>
        <link rel='stylesheet' id='camera-css'  href='<?php echo $root; ?>/assets/css/camera.css' type='text/css' media='all'/> 
        <!--login-->
        <link href="assets/css/signin.css" rel="stylesheet">
    </head>
    <body>
        <!-- Fixed navbar -->
        <div class="navbar navbar-inverse">
            <div class="container">
                <div class="navbar-header">
                    <!-- Button for smallest screens -->
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
                    <a class="navbar-brand" href="http://www.eia.edu.co">
                        <img src="<?php echo $root; ?>/assets/images/logo.png" style="width: 150px;height: 110px;" ></a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav pull-right mainNav">
                        <li class="active"><a href="index.php">Home</a></li>
                        <li><a href="login.php">Log in</a></li>
                        <li><a href="courses.php">Acerca de...</a></li>
                        <!--<li><a href="videos.html">Videos</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Pages <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="sidebar-right.html">Right Sidebar</a></li>
                                <li><a href="#">Dummy Link1</a></li>
                                <li><a href="#">Dummy Link2</a></li>
                                <li><a href="#">Dummy Link3</a></li>
                            </ul>
                        </li>!-->
                        <li><a href="contact.html">Contacto</a></li>

                    </ul>
                </div>
                <!--/.nav-collapse -->
            </div>
        </div>
        <!-- /.navbar -->
        <?php if ($this->header == NULL) { ?>
            <header id="head"><div class="container">
                    <div class="heading-text">							
                        <h1 class="animated flipInY delay1">Sistema de </h1>
                        <p>Materias Cursadas en el semestre</p>
                    </div>

                    <div class="fluid_container">                       
                        <div class="camera_wrap camera_emboss pattern_1" id="camera_wrap_4">
                            <div data-thumb="<?php echo $root; ?>/assets/images/slides/thumbs/img1.jpg" data-src="<?php echo $root; ?>/assets/images/slides/img1.jpg">
                                <h2>We develop.</h2>
                            </div> 
                            <div data-thumb="<?php echo $root; ?>/assets/images/slides/thumbs/img2.jpg" data-src="<?php echo $root; ?>/assets/images/slides/img2.jpg">
                            </div>
                            <div data-thumb="<?php echo $root; ?>/assets/images/slides/thumbs/img3.jpg" data-src="<?php echo $root; ?>/assets/images/slides/img3.jpg">
                            </div> 
                        </div> #camera_wrap_3 
                    </div> .fluid_container 
                </div>
            </header><?php }
            else
                echo $this->header;?>
        <!-- /.navbar -->
        <div id="container" aling="center" >
            <h1><?php echo $this->escape($this->title); ?></h1>
            <?php echo $this->layout()->content; ?>
        </div>
        <footer>
            <div class="container">
                <br/><br/>
            </div>
            <div class="footer2">
                <div class="container">
                    <div class="row">

                        <div class="col-md-6 panel">
                            <div class="panel-body">
<!--                                    <p class="simplenav">
                                    <a href="index.html">Home</a> | 
                                    <a href="about.html">About</a> |
                                    <a href="courses.html">Courses</a> |
                                    <a href="price.html">Price</a> |
                                    <a href="videos.html">Videos</a> |
                                    <a href="contact.html">Contact</a>
                                </p>-->
                            </div>
                        </div>

                        <div class="col-md-6 panel">
                            <div class="panel-body">
                                <p class="text-right">
                                    EIA <a href="http://eia.edu.co/" rel="develop">Ingeneria en sistemas Computacionales</a>
                                </p>
                            </div>
                        </div>

                    </div>
                    <!-- /row of panels -->
                </div>
            </div>
        </footer>

        <!-- JavaScript libs are placed at the end of the document so the pages load faster -->
        <script src="<?php echo $root; ?>/assets/js/modernizr-latest.js"></script> 
        <script type='text/javascript' src='<?php echo $root; ?>/assets/js/jquery.min.js'></script>
        <script type='text/javascript' src='<?php echo $root; ?>/assets/js/fancybox/jquery.fancybox.pack.js'></script>

        <script type='text/javascript' src='<?php echo $root; ?>/assets/js/jquery.mobile.customized.min.js'></script>
        <script type='text/javascript' src='<?php echo $root; ?>/assets/js/jquery.easing.1.3.js'></script> 
        <script type='text/javascript' src='<?php echo $root; ?>/assets/js/camera.min.js'></script> 
        <script src="<?php echo $root; ?>/assets/js/bootstrap.min.js"></script> 
        <script src="<?php echo $root; ?>/assets/js/custom.js"></script>
        <script>
            jQuery(function () {

                jQuery('#camera_wrap_4').camera({
                    transPeriod: 500,
                    time: 3000,
                    height: '600',
                    loader: 'false',
                    pagination: true,
                    thumbnails: false,
                    hover: false,
                    playPause: false,
                    navigation: false,
                    opacityOnGrid: false,
                    imagePath: '<?php echo $root; ?>/assets/images/'
                });

            });

        </script>
    </body>
</html>
